### ISSUE TITLE
创建完的vm，curl无法联网，ping是正常的

### ISSUE THREAD

**Issue by 95i** [spiritLHLS/pve#10]
![image](https://github.com/spiritLHLS/pve/assets/54938994/7fbaaaf6-7b2f-405b-bf38-07418bc9af40)

**Comment by spiritLHLS** [comment]
刚刚修复了一下，之前去重iptables规则的时候，命令写的有问题，现在应该没问题了，删除虚拟机后，重新下载开机脚本，再开一次，应该就好了

**Comment by spiritLHLS** [comment]
还有问题再反馈吧
