### ISSUE TITLE
Debain 12, 原来使用无线网卡正常访问网络，安装 PVE 后无法联网，请问是什么原因？(国内本地DIY的物理机器，非独服/云服务器)

### ISSUE THREAD

**Issue by workspace-git** [spiritLHLS/pve#12]
如题

**Comment by spiritLHLS** [comment]
请给出查询截图 #11 中所写的那些东西请查询一下

**Comment by workspace-git** [comment]
![图像](https://github.com/spiritLHLS/pve/assets/63133117/88e74d57-2476-4ea1-8834-1d6eb2c3cb41)

**Comment by workspace-git** [comment]
![图像](https://github.com/spiritLHLS/pve/assets/63133117/86a1eaeb-6e87-43db-aa25-68389817f165)

**Comment by spiritLHLS** [comment]
你
```
curl ip.sb
```
显示的是什么报错？能截图看看吗？

**Comment by workspace-git** [comment]
> 你
> 
> ```
> curl ip.sb
> ```
> 
> 显示的是什么报错？能截图看看吗？

could not resolve host: ip.sb

**Comment by spiritLHLS** [comment]
> > 你
> > ```
> > curl ip.sb
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 显示的是什么报错？能截图看看吗？
> 
> could not resolve host: ip.sb

```
cat /etc/resolv.conf
```

**Comment by spiritLHLS** [comment]
执行
```
resolvconf -a vmbr0 < /etc/resolv.conf
```
看看

**Comment by workspace-git** [comment]
> resolvconf

没有 resolvconf 这个命令 。。。

**Comment by workspace-git** [comment]
我现在重装了系统，直接安装了 pve 8.0.2，但配置无线网络还是失败，我的有线网卡不知道为什么识别不出来，所以机器是处在无网的状态

**Comment by spiritLHLS** [comment]
> 没有 resolvconf 这个命令 。。。

没有 resolvconf 这个命令还行，dns没加载，网址解析不出来，你ping一下某个国内IP估计是通的

**Comment by workspace-git** [comment]
我现在 ping 网关都是 Unreachable

**Comment by workspace-git** [comment]
有微信吗？方便加一下吗

**Comment by spiritLHLS** [comment]
你是物理鸡还是云服务器？是国内机器还是国外机器？头一次见你这种情况

**Comment by workspace-git** [comment]
diy 的一个本地物理机

**Comment by spiritLHLS** [comment]
草，那没辙，我这个主要是适配的 云服务器 和 云上的 独服 的，一般他们宿主机的后台是 IPMI、VMWARE、Proxmox VE、virtualizor solusvm 控制的，本地DIY的我就不清楚了，未作适配

**Comment by spiritLHLS** [comment]
恩山论坛 或者 PVE官方的论坛问一下吧，捣鼓本地硬件的，后续有空本地服务器这方面我再适配一下吧

**Comment by spiritLHLS** [comment]
如果是本地服务器，你直接下PVE官网的ISO安装不就得了，本地想怎么导入就怎么导入，无需限定通过网络安装PVE
