### ISSUE TITLE
开设纯IPV6地址的虚拟机:指定的VMID  和最后生成的IPV6地址关系如何？（小白问题)

### ISSUE THREAD

**Issue by ainp** [spiritLHLS/pve#13]
新开的CrunchBits的特价机，IPV6 地址：2606:a8c0:3:402::/64（2606:a8c0:3:402::a ～2606:a8c0:3:402::3b 共51个),用了https://github.com/leitbogioro/Tools的脚本安装了debian 12。用了您的**开设纯IPV6地址的虚拟机**, 最后给出了如下的指示：
161 test1 oneclick123 1 1024 10 debian12 local 2606:a8c0:3:402::161， 这个ipv6地址2606:a8c0:3:402::161很明显超出了机器的范围，这个是ipv6地址吗？真正的ipv6 地址在哪？（我试了一下把VMID设置成10,没有设置成功，说有错误）,麻烦了

**Comment by ainp** [comment]
还有就是对VMID 有什么要求吗（范围）？

**Comment by ainp** [comment]
sorry! 我自己认为错了

**Comment by spiritLHLS** [comment]
ipv6在 CrunchBits 的原生系统中有问题，D后未测试有没有问题，有问题再反馈吧
