### ISSUE TITLE
开设纯IPV6地址的虚拟机（出新问题了)

### ISSUE THREAD

**Issue by ainp** [spiritLHLS/pve#15]
![截屏2023-11-22 18 02 59](https://github.com/spiritLHLS/pve/assets/9693302/8b5d5dc0-2c15-48f8-b313-3e97a193e1f0)

**Comment by ainp** [comment]
改之前的网路配置如下:
![截屏2023-11-22 17 07 22](https://github.com/spiritLHLS/pve/assets/9693302/5ca839dd-add2-44ff-b30d-b83db88e43f9)

**Comment by ainp** [comment]
vps 提供了51个ipv6地址如下：
![virt crunchbits com_server_c9f07a02-a11e-46d3-a387-8fb3b5029d03](https://github.com/spiritLHLS/pve/assets/9693302/cb2adc15-b752-4684-8d70-25b2b4e3c8d2)

**Comment by spiritLHLS** [comment]
我测试的没这个问题，你是不是没有执行网关设置命令

**Comment by spiritLHLS** [comment]
D成debian12的静态版本就行，还有那个后台v6你只需要enable一个v6地址就行了，别enable一堆，其他自动添加的

**Comment by spiritLHLS** [comment]
> ![截屏2023-11-22 18 02 59](https://user-images.githubusercontent.com/9693302/284866825-8b5d5dc0-2c15-48f8-b313-3e97a193e1f0.png)

这个截图没有后面vmbr1和vmbr2

**Comment by ainp** [comment]
> > ![截屏2023-11-22 18 02 59](https://user-images.githubusercontent.com/9693302/284866825-8b5d5dc0-2c15-48f8-b313-3e97a193e1f0.png)
> 
> 这个截图没有后面vmbr1和vmbr2
没有了

**Comment by ainp** [comment]
> 我测试的没这个问题，你是不是没有执行网关设置命令

我执行了您的 “自动配置宿主机的网关”

**Comment by spiritLHLS** [comment]
> > 我测试的没这个问题，你是不是没有执行网关设置命令
> 
> 我执行了您的 “自动配置宿主机的网关”

我测试的具体流程 后台仅开启一个IPV6地址，其他不enable --> 然后通过官方后台重置为debian12 --> 使用常见问题答疑的命令D为纯净的Debian12系统 --> 开设Swap，然后使用一键脚本测试环境 --> 执行主体安装命令 --> 按照要求重启服务器 --> 再次连接上SSH后等待有20秒 --> 执行主体安装命令 --> 执行预配置环境命令 --> 登录web的8003页面 --> 测试登录无问题 --> 重启服务器 --> 再次连接上SSH后等待有1分钟，且登录web的8003页面无异常 --> 执行自动配置宿主机的网关的命令 --> 测试开纯IPV6地址的容器/虚拟机测试

**Comment by ainp** [comment]
我严格按照你的要求操作了一遍，可以ping通 ipv6地址：root@pve:~# ping6 blog.ainp.gay
PING blog.ainp.gay(2606:a8c0:3:402::101 (2606:a8c0:3:402::101)) 56 data bytes
64 bytes from 2606:a8c0:3:402::101 (2606:a8c0:3:402::101): icmp_seq=1 ttl=64 time=1.43 ms
64 bytes from 2606:a8c0:3:402::101 (2606:a8c0:3:402::101): icmp_seq=2 ttl=64 time=0.550 ms
64 bytes from 2606:a8c0:3:402::101 (2606:a8c0:3:402::101): icmp_seq=3 ttl=64 time=0.342 ms
64 bytes from 2606:a8c0:3:402::101 (2606:a8c0:3:402::101): icmp_seq=4 ttl=64 time=0.379 ms
64 bytes from 2606:a8c0:3:402::101 (2606:a8c0:3:402::101): icmp_seq=5 ttl=64 time=0.384 ms
64 bytes from 2606:a8c0:3:402::101 (2606:a8c0:3:402::101): icmp_seq=6 ttl=64 time=0.564 ms
但还是一样，无法SSH，PVE里终端可以登入，但应该仍是无法联网。要么我把vps给你。你来看看怎样

**Comment by ainp** [comment]
宿主的网路配置如下：
![截屏2023-11-22 下午10 14 51](https://github.com/spiritLHLS/pve/assets/9693302/4e609d49-27de-4f5d-8352-65179dfaa9a2)

**Comment by ainp** [comment]
虚拟机的网路配置：
![截屏2023-11-22 下午10 17 42](https://github.com/spiritLHLS/pve/assets/9693302/318f03d2-def6-41f0-8d50-205d4c8b6a38)

**Comment by ainp** [comment]
vps后台ipv6地址好像是从 A开始的
![截屏2023-11-22 下午10 21 20](https://github.com/spiritLHLS/pve/assets/9693302/83db1260-f791-42b4-85b8-f36363d092f3)

**Comment by spiritLHLS** [comment]
> 虚拟机的网路配置： ![截屏2023-11-22 下午10 17 42](https://user-images.githubusercontent.com/9693302/284933758-318f03d2-def6-41f0-8d50-205d4c8b6a38.png)

这个配置就不对了402那个是你的address没错，但gateway不对

**Comment by spiritLHLS** [comment]
> 我严格按照你的要求操作了一遍，可以ping通 ipv6地址：root@pve:~# ping6 blog.ainp.gay PING blog.ainp.gay(2606:a8c0:3:402::101 (2606:a8c0:3:402::101)) 56 data bytes 64 bytes from 2606:a8c0:3:402::101 (2606:a8c0:3:402::101): icmp_seq=1 ttl=64 time=1.43 ms 64 bytes from 2606:a8c0:3:402::101 (2606:a8c0:3:402::101): icmp_seq=2 ttl=64 time=0.550 ms 64 bytes from 2606:a8c0:3:402::101 (2606:a8c0:3:402::101): icmp_seq=3 ttl=64 time=0.342 ms 64 bytes from 2606:a8c0:3:402::101 (2606:a8c0:3:402::101): icmp_seq=4 ttl=64 time=0.379 ms 64 bytes from 2606:a8c0:3:402::101 (2606:a8c0:3:402::101): icmp_seq=5 ttl=64 time=0.384 ms 64 bytes from 2606:a8c0:3:402::101 (2606:a8c0:3:402::101): icmp_seq=6 ttl=64 time=0.564 ms 但还是一样，无法SSH，PVE里终端可以登入，但应该仍是无法联网。要么我把vps给你。你来看看怎样

tg联系我，留言即可，明日查看

**Comment by spiritLHLS** [comment]
Fixed
