### ISSUE TITLE
甲骨文arm云服务器安装后断网及LXC控制台显示问题

### ISSUE THREAD

**Issue by ni7ht** [spiritLHLS/pve#16]
环境：甲骨文arm VPS debian 12
问题1：按脚本安装后开机可公网登陆，但执行配置脚本后管理地址变为内网地址无法公网登陆。
问题2：容器控制台显示问题，网页集成控制台显示不全见图片console0
![console0](https://github.com/spiritLHLS/pve/assets/37174285/0f42d254-198d-4c83-9487-b39b4aa5d818)

             单独打开可显示全见图片console1。
![console1](https://github.com/spiritLHLS/pve/assets/37174285/209cd28e-c1dd-4195-b133-3d3bedf89c01)

**Comment by spiritLHLS** [comment]
若方便的话联系 https://t.me/spiritlhl_bot 方便发图交流

**Comment by spiritLHLS** [comment]
多物理网卡的情况以及非适配的DD程序=我暂时无法适配，情况太罕见了
