### ISSUE TITLE
原有的grub.cfg 好像不起作用了，双系统boot丢失

### ISSUE THREAD

**Issue by ainp** [spiritLHLS/pve#17]
我看了 /etc/grub.d/000_proxmox_boot_header注释，好像原有的grub.cfg 不起作用了，我安装了双系统(windows和Linux),windows就无法引导了，可以有方法引导原有的双系统吗？（我看原来grub 都在）

**Comment by spiritLHLS** [comment]
[build_backend.sh](https://github.com/spiritLHLS/pve/blob/9e570f1d4dea5fcb061f0a8892682e1ed3cc396c/scripts/build_backend.sh#L73)

估计是这个造成的，不执行本脚本即可，自己注释掉对应的部分再执行或自己手动创建资源池解决
