### ISSUE TITLE
在不使用一键脚本的情况下进行 nat ipv4 映射

### ISSUE THREAD

**Issue by jgc9527** [spiritLHLS/pve#2]
能否添加一个脚本用来转发小鸡的端口，因为在后续使用小鸡时会添加其他的端口，这是在一开始想不到的。
使用需要一个转发脚本来转发

列
nat ipv4
内网ip
内网端口
外网端口
协议

**Comment by spiritLHLS** [comment]
默认已带内外网转发端口，TCP和UDP都转了的

**Comment by jgc9527** [comment]
我想的应该是另开一个脚本来完成这些操作

**Comment by jgc9527** [comment]
> 我想的应该是另开一个脚本来完成这些操作

在不使用一键开设脚本的时候来nat

**Comment by spiritLHLS** [comment]
只能说有空再说，毕竟做本项目时基本没怎么考虑在别人的设置上再增加什么设置、兼容什么其他的人为设置啥的，一切追求自动化

**Comment by spiritLHLS** [comment]
你需要
https://github.com/csznet/goForward
等类似项目，本项目暂时没有二开ipt映射逻辑的想法
