### ISSUE TITLE
kvm批量开设的没有root权限？

### ISSUE THREAD

**Issue by FugitiveL** [spiritLHLS/pve#6]
lxc批量开设的直接就是用root登录！
kvm的给了不是root的用户名！用密码也提升不了root权限！
但是单独开的kvm就可以直接用root登录！

**Comment by spiritLHLS** [comment]
？批量kvm用的是开单独的KVM的脚本，有问题应该是一起有问题的，是不是后台的cloud-init没搞定，你多等会再试试，如果还有问题反馈一下KVM你用的镜像

**Comment by spiritLHLS** [comment]
批量开设KVM后需要等待一会，需要等待每个虚拟机的环境初始化，这个过程每个虚拟机自开机起计算大概需要5~10分钟，具体看配置和网速

**Comment by FugitiveL** [comment]
单开用单开命令开的debian11
批量用的批量脚本默认的debian10
vm203  GZmv  145bb0fa7  40004  40005  40006 50026  50051
批量开的kvm只能用用户名GZmv密码145bb0fa7登录su -之后输入145bb0fa7密码不对
直接用root登录也提示密码不对

**Comment by FugitiveL** [comment]
lxc批量开的就没有给用户名

**Comment by FugitiveL** [comment]
./buildvm.sh 102 root 1234567 1 512 10 40001 40002 40003 50000 50025 debian11
单独开kvm我直接填写的root为用户名

**Comment by FugitiveL** [comment]
./buildvm.sh $vm_num $user $password $cpu_nums $memory_nums $disk_nums $ssh_port $web1_port $web2_port $port_start $port_end debian10

我把$user改成root倒是可以了

**Comment by spiritLHLS** [comment]
> 单开用单开命令开的debian11 批量用的批量脚本默认的debian10 vm203 GZmv 145bb0fa7 40004 40005 40006 50026 50051 批量开的kvm只能用用户名GZmv密码145bb0fa7登录su -之后输入145bb0fa7密码不对 直接用root登录也提示密码不对

不要su啊，直接```sudo -i```就切换了的，不用```su root```的

**Comment by FugitiveL** [comment]
> > 单用单开命令打开的debian11 批量使用的批量默认的debian10 vm203 GZmv 145bb0fa7 40004 40005 40006 50026 50051 批量打开的kv m只能用用户名GZmv密码145bb0fa7登录su -之后输入145bb0fa7密码不对直接用root登录也提示密码不对
> 
> 不要su啊，直接`sudo -i`切换了的，不用`su root`的

好吧~_~误会了我还不太会！

**Comment by spiritLHLS** [comment]
说明里我增加了这块的描述，免得以为没root权限
