### ISSUE TITLE
能不能加个功能！主机两个磁盘！用你的脚本只能在第一次磁盘创建虚拟机！

### ISSUE THREAD

**Issue by FugitiveL** [spiritLHLS/pve#7]
![image](https://github.com/spiritLHLS/pve/assets/119951031/8946a2ce-1fa9-4920-884c-f0f2528a1f60)

**Comment by spiritLHLS** [comment]
可以考虑这部分增加这个功能，目前我使用并测试的大部分是VPS而不是挂载了第二个盘的独服，后续会添加这部分功能

**Comment by FugitiveL** [comment]
我自己改了一下但是不行！你能看下吗？或者留个联系方式？

**Comment by spiritLHLS** [comment]
别急。。。本人维护的项目较多，基本都是轮着来推进的，这周六日我再看看吧

**Comment by spiritLHLS** [comment]
已修改添加对应设置，你可以试试了

https://github.com/spiritLHLS/pve/commit/c4ceeaf87b3fac1b6801976b7084d0161d4e6f1d

https://github.com/spiritLHLS/pve/commit/3c596fa339eb014da290a8d2addd9ab19080e060

**Comment by FugitiveL** [comment]
我昨天已经研究好了！

**Comment by FugitiveL** [comment]
希望后期再加个可以分配IP的功能

**Comment by spiritLHLS** [comment]
> 希望后期再加个可以分配IP的功能

目前V6还没搞好，开纯V6和带V6的虚拟机实现批量后，会做多IP的适配的，不急

> 我昨天已经研究好了！

如果脚本还有问题再反馈吧，暂时关闭该线程
